sudo: required
services:
- docker
language: bash

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t the-image .
  - docker run -td --name nethack the-image
  - docker ps -f name=nethack
