

sudo: required
services:
- docker
language: bash
env:
  - VERSION=6.11
  - VERSION=8.1
script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t the-image .
  - docker run -td --name nethack the-image
  - docker ps -f name=nethack
